In [14]:
list_of_items = [3,2,5,6,7]
list_of_items2 = [3,2,5,6,7]

In [15]:
type(list_of_items)

list

In [10]:
import numpy as np

In [11]:
items = np.array([3,2,5,6,7])
items_2 = np.array([3,2,5,6,7])

In [12]:
items

array([3, 2, 5, 6, 7])

In [13]:
items_2

array([3, 2, 5, 6, 7])

In [16]:
type(items)

numpy.ndarray

In [17]:
items * items_2

array([ 9,  4, 25, 36, 49])

In [18]:
# Knowing the size of a numpy array

items.size

5

In [19]:
# Knowing the shape of a numpy array - know the dimension of that array. 1 dimensional array with 5 columns and 1 row

items.shape 

(5,)

In [20]:
# Create a 2 dimensional array - 2 columns and 5 rows. ([[column1],[column2]])

item_3 = np.array([[3,2,5,6,7],[3,2,5,6,7]])

In [21]:
item_3.shape

(2, 5)

In [22]:
item_3

array([[3, 2, 5, 6, 7],
       [3, 2, 5, 6, 7]])

In [24]:
# ndim to give dimension of any array

item_3.ndim

2

In [27]:
# Creating a 3 dimensional array - can be described by 3 things -  x,y,z coordinates
# When you break down an array you need to have everything in outer []

item_4 = np.array([[[3,2,5,6,7],[3,2,5,6,7]],[[3,2,5,6,7],[3,2,5,6,7]]])

In [28]:
item_4.ndim

3

In [29]:
item_4

array([[[3, 2, 5, 6, 7],
        [3, 2, 5, 6, 7]],

       [[3, 2, 5, 6, 7],
        [3, 2, 5, 6, 7]]])

In [30]:
item_4.shape

(2, 2, 5)

In [31]:
# Accessing items with ndarrays 

# Accessing 1-dimensional array: items = np.array([3,2,5,6,7])
# Access 3
items[0]

3

In [33]:
# Accessing 2-dimensional array: item_30 = np.array([[23,45,4],[20,43,4]])
# Access 45
item_30 = np.array([[23,45,4],[20,43,4]])

item_30[0,1]

45

In [44]:
# Accessing 2-dimensional array: item_30 = np.array([[23,45,4],[20,43,4]])
# Access 20,4
item_30 = np.array([[23,45,4],[20,43,4]])

item_30[1,[0,2]] #in row 1 return column 0 and 2


array([20,  4])

In [52]:
# Accessing 3-dimensional array
# item_4 = np.array([[[23,45,5],[23,45,5]],[[3,5,4],[23,5,4]]])
# Access 3

item_4[1,0,0] #in row 1 return column 0 and 2

3

In [73]:
# Accessing 3-dimensional array
# item_4 = np.array([[[23,45,5],[23,45,5]],[[3,5,4],[23,5,4]]])
# Access 45,45,5,5

item_4 = np.array([[[23,45,5],[23,45,5]],[[3,5,4],[23,5,4]]])
item_4[0:,0:,1] # : access all the rows, within that row level we want to access all the rows in the inner so : again, 
#to get the position within that level we put 1 (for 1 in each level). : access everything, 0:  access everything after index 0

array([[45, 45],
       [ 5,  5]])

In [80]:
# Changing items within ndarray

# 1-dimensional array: items = np.array([23,45,4])
items = np.array([23,45,4])

# Change 45 to 5
items[1]=5
items

array([23,  5,  4])

In [81]:
# Changing items within ndarray
# 3-dimensional array
# item_4 = np.array([[[23,45,5],[23,45,5]],[[3,5,4],[23,5,4]]])
# change all items in the middle column to 8,9,10,11

item_4 = np.array([[[23,45,5],[23,45,5]],[[3,5,4],[23,5,4]]])
item_4[0:,0:,1] = [[8,9],[10,11]]
item_4

array([[[23,  8,  5],
        [23,  9,  5]],

       [[ 3, 10,  4],
        [23, 11,  4]]])